### ISSUE TITLE
Broncas para a primeira aula

### ISSUE THREAD

**Issue by leouieda** [lagex/geofisica2#9]
- Traduzir texto e não citar é plágio.
- Plágio = 0.
- Google translate não é perfeito (ver figura abaixo). Ao menos corrija a tradução para não ficar na cara. E Google translate + Wikipedia = plágio = 0.
- Copiar texto do site da disciplina é inútil (e plágio). Não me faça perder meu tempo lendo algo que fui eu que escrevi.
- Se for colar, faça direito. **Não**: copiar artigo do professor, entregar relatório igual, mudar duas palavras não é o mesmo que escrever.
-  Texto igual (ver acima) = 0.
- Argumento circular não é argumento pois quando esse circula ele não é válido para argumentação

![maldito google translate](https://cloud.githubusercontent.com/assets/290082/6060274/692d66fc-ad22-11e4-8898-9ae1a5f28a1d.png)

**Comment by birocoles** [comment]
Perfeito @leouieda !!!!!!!

**Comment by hbueno** [comment]
Muito bom!
@leouieda sugiro uma issue para "esclarecer" o que são direitos autorais!

**Comment by leouieda** [comment]
@hbueno isso já cai fora do escopo da matéria e habilidade do professor. Eles tem uma matéria de legislação (não sei se cobre isso).

**Comment by eusoubrasileiro** [comment]
github é também diversão em ver a vida dos nossos colegas professores! rs

**Comment by leouieda** [comment]
Mais um (e meu favorito até agora):
- Argumento circular não é argumento pois quando esse circula ele não é válido para argumentação.

Inspirado em (adaptado): "Quando aplicamos erro nos dados, a derivada fica com um erro muito mais por que a derivada amplifica o erro."
